name: Bug Report
description: File a bug report
title: "Issue"
labels: ["issue"]
body:
  - type: input
    id: url
    attributes:
      label: Site URL
      description: The home page of the live web site you built. _[parser:url]_
      placeholder: e.g. https://www.zachleat.com/
    validations:
      required: true
